name: Auto translate TS

on:
  push:
    paths:
      - "**.ts"

jobs:
  translate:

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run translation script
        env:
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
        run: |
          python scripts/auto_translate_ts.py

      - name: Commit changes
        run: |

          git config user.name "translation-bot"
          git config user.email "bot@github.com"

          if git diff --quiet; then
            echo "No translation changes"
            exit 0
          fi

          BRANCH=translation-bot-${{ github.run_id }}

          git checkout -b $BRANCH

          git add .

          git commit -m "Automatic translations using DeepL"

          git push origin $BRANCH

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: Automatic translations update
          body: |
            Automatic translations generated through DeepL Free API.

            Please review before merging.
          branch: translation-bot-${{ github.run_id }}