name: Auto translate TS

on:
  push:
    paths:
      - "**.ts"

jobs:
  translate:

    if: github.actor != 'translation-bot'

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Run translation script
        env:
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
        run: python scripts/auto_translate_ts.py

      - name: Commit translations
        run: |

          git config user.name "translation-bot"
          git config user.email "bot@github.com"

          if git diff --quiet; then
            echo "No changes"
            exit 0
          fi

          git add .
          git commit -m "Automatic translations using DeepL"
          git push